
version: "2.3"
services: 
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'localhost:8082'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8082'
    ports:
      - '8082:8082'
    # volumes:
    #   - '$GITLAB_HOME/config:/etc/gitlab'
    #   - '$GITLAB_HOME/logs:/var/log/gitlab'
    #   - '$GITLAB_HOME/data:/var/opt/gitlab'