version: "2.3"
services: 
  nginx:
    container_name: app_nginx
    build: ./nginx
    expose:
      - "8080"
    ports:
      - '8080:8080'
    depends_on: 
      - golang
    environment: 
      - ENV=${APP_MODE} 
  golang:
    container_name: app_golang
    build: .
    environment: 
      - ENV=${APP_MODE}
      - PORT=${PORT}